<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <UserSecretsId>dotnet-InvoiceLens.OpenInvoiceMock-5f9c6b7a-4a8f-4d38-a0d1-9b3f6d4bb2b2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InvoiceLens.Infrastructure\InvoiceLens.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Data\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Storage\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
